export interface Music {
  tone: string;
  name: string;
  src: string;
  studio?: boolean;
  caminho?: boolean;
}

// export const musics: Music[] = [
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "G",
//     name: "Abraço bom",
//     src: "Abraço bom (G).mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "E",
//     name: "A alegria do senhor é nossa força",
//     src: "A alegria do senhor é nossa força (E).mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "G",
//     name: "A pé seco",
//     src: "A pé seco (G).mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "Dm",
//     name: "A Vitória",
//     src: "a vitoria.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "D",
//     name: "Bom é Louvar",
//     src: "bom e louvar.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "D",
//     name: "Como vai",
//     src: "como vai.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "chuva de graça",
//     src: "chuva de grava (studio) - C.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Dança da amizade",
//     src: "danca da amizade.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "F",
//     name: "derrama o ter amor",
//     src: "derrama o ter amor (studio) - F.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "F",
//     name: "Derrama o teu amor aqui",
//     src: "Derrama o teu amor aqui (F).mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "C",
//     name: "Espirito Santo resoupa",
//     src: "espirito santo repousa.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "D",
//     name: "Eternos amigos",
//     src: "eternos amigos.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "C",
//     name: "Eu espero",
//     src: "eu espero.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "E",
//     name: "Eu quero me apaixonar",
//     src: "eu quero me apaixonar.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "E",
//     name: "enviai",
//     src: "enviai.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "D",
//     name: "Estatua de sal",
//     src: "Estatua de sal (D).mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "C",
//     name: "Estrangeiro aqui",
//     src: "Estrangeiro aqui (C) .mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "D",
//     name: "Eu quero ser de Deus",
//     src: "Eu quero ser de Deus (D) .mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Exército de Deus",
//     src: "Exército de Deus.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "Am",
//     name: "Marca da Vitória",
//     src: "Marca da Vitória (Am) .mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "E",
//     name: "Melo dos Animais",
//     src: "Melo dos Animais - E.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Minha essência",
//     src: "Minha Essência.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Minha essência (Axé)",
//     src: "minha essencia axe.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Minha essência (Reggae)",
//     src: "minha essencia reggae.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "D",
//     name: "Molinho para Jesus",
//     src: "molinho.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: false,
//     tone: "Am",
//     name: "Nosso General é Cristo",
//     src: "Nosso general (Am).mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "Am",
//     name: "Nosso General é Cristo",
//     src: "Nosso General é Cristo.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "o amor",
//     src: "o amor (Studio) - C.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "Bm",
//     name: "O Senhor é Rei",
//     src: "senhor e rei.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "passa fogo",
//     src: "vem fogo.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "Am",
//     name: "passeio de caranguejo",
//     src: "passeio e caranguejo - Am.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "E",
//     name: "Pescador de Cristo",
//     src: "pescador.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "G",
//     name: "Pipoca",
//     src: "pipoca.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "E",
//     name: "Pirado por Jesus",
//     src: "pirado.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "Reggae do missionário",
//     src: "Reggae do Missionário.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C > E",
//     name: "Pot Pourri - Reggae do Míssionário e Tum tum tum",
//     src: "Pot Pourri - Reggae do Míssionário e Tum tum tum.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "Pot Pourri 1",
//     src: "potpourri.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "D",
//     name: "Pot Pourri - Uma entre todas e Quem é essa",
//     src: "maria.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "E",
//     name: "qual é a chave",
//     src: "qual e a chave.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "G",
//     name: "so por ti jesus",
//     src: "so por ti jesus.mp3",
//   },
//   {
//     // studio: false,
//     // caminho: true,
//     tone: "C",
//     name: "tua família",
//     src: "tua familia.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "C",
//     name: "Templo Vivo",
//     src: "Templo Vivo (studio) - C.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "D",
//     name: "Se for para agradar a Deus",
//     src: "nana.mp3",
//   },
//   {
//     // studio: true,
//     //  caminho: false,
//     tone: "D",
//     name: "txuco",
//     src: "txuco1.mp3",
//   },
//   {
//     // studio: true,
//     // caminho: false,
//     tone: "D",
//     name: "vamos cantar",
//     src: "vamos cantar.mp3",
//   },
// ];
